{% set version = "0.10.1" %}

package:
  name: terminado
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/terminado/terminado-{{ version }}.tar.gz
  sha256: 89d5dac2f4e2b39758a0ff9a3b643707c95a020a6df36e70583b88297cd59cbe

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - ptyprocess  # [not win]
    - pywinpty >=1.1.0  # [win]
    - tornado >=4

test:
  imports:
    - terminado
  requires:
    - pip
    - posix  # [win]
    - pytest
    - pytest-cov
  commands:
    # see run_test.py for more
    - python -m pip check

about:
  home: https://github.com/jupyter/terminado
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Terminals served by tornado websockets
  description: |
    Terminado is a Tornado websocket backend for the term.js Javascript
    terminal emulator library.
  doc_url: http://terminado.readthedocs.org/en/latest/
  doc_source_url: https://github.com/takluyver/terminado/blob/master/doc/index.rst
  dev_url: https://github.com/takluyver/terminado

extra:
  recipe-maintainers:
    - blink1073
    - pelson
    - takluyver
    - ocefpaf
