{% set version = "0.6" %}

package:
  name: terminado
  version: {{ version }}

source:
  fn: terminado-{{ version }}.tar.gz
  url: https://github.com/takluyver/terminado/archive/0.6.tar.gz
  sha256: 6a1cfe8ede41962827ca8260bc64f387de85be62fd4e936bdde2ecf2a433931c

build:
  number: 0
  script: python setup.py install
  skip: True  # [win]

requirements:
  host:
    - python
  run:
    - python
    - ptyprocess
    - tornado >=4

test:
  imports:
    - terminado

  requires:
    - nose

  commands:
    # Failing test on osx: https://github.com/conda-forge/staged-recipes/pull/313#issuecomment-208426267
    # Failing test on Linux (due to ps1 of conda? having conda activate in bashrc? One of those two!
    # File "/home/ray/m/conda-bld/terminado_1503494513344/_test_env_placehold_.../lib/python2.7/site-packages/terminado/tests/basic_test.py", line 84, in get_pid
    # ..
    # self.write_stdin("echo $$\r")
    # (stdout, extra) = yield self.read_stdout()
    # pid = int(stdout.split('\n')[1])
    # ..
    #  ValueError: invalid literal for int() with base 10: '\x1b]777;notify;Command completed;echo $$\x07\x1b]0;ray@localhost:~/m/conda-bld/terminado_1503494513344/test_tmp\x07\x1b]7;file://localhost.localdomain/home/ray/m/conda-bld/terminado_1503494513344/test_tmp\x07(root) ec'
    - nosetests terminado  # [not osx and not linux]

about:
  home: http://github.com/mitsuhiko/markupsafe
  license: BSD 3-clause
  summary: Terminals served by tornado websockets
  description: |
    Terminado is a Tornado websocket backend for the term.js Javascript
    terminal emulator library.
  doc_url: http://terminado.readthedocs.org/en/latest/
  doc_source_url: https://github.com/takluyver/terminado/blob/master/doc/index.rst
  dev_url: https://github.com/takluyver/terminado

extra:
  recipe-maintainers:
    - pelson
    - takluyver 
