travis:
  secure:
    BINSTAR_TOKEN: k7DB5b91Sk54ao6w1DQXjlGjX/iseLebD3HeceL4fEDVQrIVT+EMsVrL0M49TxsPUKcBjW2rHslXvhoV/kjZux1biut8Lmr1gnReid9Bp5EmiuIhifuhibzt56S0Tuu09oNwZPtighijFnfmdMwLtzqnpS7CwJyVeiEogbXAW5O6WlTMH+Tj2hZpFvdJpoRXMmhvS6V/V5vxhfaGFaA/pGGouCf0zOZCjcSkCi9HxCbrFJxNskXFreVz/Tq56mKWCQeuvsVkqT0c9pxdjEj0+VJJuYhpcyyJfgxdrf1lFwmfGsA8nF50Se1noTDJGTJpnianyvce2r/zDnfhpKs9B73lE7g3dLGtxNL2xalMx/NUFt2kFw2B65ycbr5+ujDpDmqTXfpXjVLcpzKM9uF7Gy2dcoC5h6FLO+K9aWkpee3/BfXiUfu1pPz+0EdP4LZ335MuGs+dgFJVrCUJ/Uj8WfaCJVgbxq120FbBfviWA0MgQ9DgIJGXmLXlPzEqinnYbviY95PlBHN+etWS0dBe/rP7MvKlGuisQF8Q3DrzkLGTj2N8Kjlxe5CQQo2E/ArA8CGQv4kRRS8ROnSVyfJO/tCEoQW57zK+oWV4pg3wyvKof7uNxExOk6z2jpAYQXCBm8dWKy+9XZhIYai3A4y7l14npe7LjUW1xzEDqiuglBw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
